backend-flask/app/__init__.py
from flask import Flask, render_template
from config import Config
from .site.routes import site
from .auth.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder


app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

backend-flask/app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Whiskey, whiskey_schema, whiskeys_schema

api = Blueprint('api', __name__, url_prefix='/api')

# Works
@api.route('/data')
def getdata():
    return{'pecan': 'pie'}

# Create / POST 
@api.route('/whiskeys', methods = ['POST'])
@token_required
def create_whiskey(current_user_token):
    data = request.get_json()
    name = data.get('name')
    category = data.get('category')
    distillery = data.get('distillery')
    bottler = data.get('bottler')
    bottling_series = data.get('bottling_series')
    year_bottled = data.get('year_bottled')
    strength = data.get('strength')
    size = data.get('size')
    notes = data.get('notes')

    # category = request.json['category']
    # distillery = request.json['distillery']
    # bottler = request.json['bottler']
    # bottling_series = request.json['bottling_series']
    # year_bottled = request.json['year_bottled']
    # strength = request.json['strength']
    # size = request.json['size']
    # notes = request.json['notes']
    user_token = current_user_token.token
    

    print(f'SuperTest (token): {current_user_token.token}')

    whiskey = Whiskey(name,category,distillery,bottler,bottling_series,year_bottled,strength,size,notes, user_token=user_token)

    db.session.add(whiskey)
    db.session.commit()

    response = whiskey_schema.dump(whiskey)
    return jsonify(response)
# Read / GET
@api.route('/whiskeys', methods = ['GET'])
@token_required
def get_whiskey(current_user_token):
    a_user = current_user_token.token
    whiskeys = Whiskey.query.filter_by(user_token = a_user).all()
    response = whiskeys_schema.dump(whiskeys)
    return jsonify(response)

# Read / GET - Specific ID
@api.route('/whiskeys/<id>', methods = ['GET'])
@token_required
def get_whiskey_two(current_user_token, id):
    newt = current_user_token.token
    if newt == current_user_token.token:
        whiskey = Whiskey.query.get(id)
        response = whiskey_schema.dump(whiskey)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401
    

# update endpoint
@api.route('/whiskeys/<id>', methods = ['POST'])
@token_required
def update_whiskey(current_user_token, id):
    req = request.get_json()
    whiskey = Whiskey.query.get(id)
    whiskey.name = req['name']
    whiskey.category = req['category']
    whiskey.distillery = req['distillery']
    whiskey.bottler = req['bottler']
    whiskey.bottling_series = req['bottling_series']
    whiskey.year_bottled = req['year_bottled']
    whiskey.strength = req['strength']
    whiskey.size = req['size']
    whiskey.notes = req['notes']
    whiskey.user_token = current_user_token.token

    db.session.commit()
    response = whiskey_schema.dump(whiskey)
    return jsonify(response)

# delete endpoint
@api.route('/whiskeys/<id>', methods = ['DELETE'])
@token_required
def delete_whiskey(current_user_token, id):
    whiskey = Whiskey.query.get(id)
    db.session.delete(whiskey)
    db.session.commit()
    response = whiskey_schema.dump(whiskey)
    return jsonify(response)

backend-flask/app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

backend-flask/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&family=Young+Serif&display=swap" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" src="../static/css/main.css">
    <title>Wispy Whiskey</title>
</head>

<body>
    <nav class="navbar navbar-expand bg-light navbar-light py-3 fixed-top">
        <div class="container-fluid">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Whiskey Collection</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- Mysterious placeholder comment! -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>

</html>

backend-flask/app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>